# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['dev']
        #- ['feature/*','**']
    pull_request:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v3 # action checks-out your repository under $GITHUB_WORKSPACE , so your workflow can access it.
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Run Checks
              uses: actions/run-checks@v2
            - name: Run CI command
              run: npm ci
            - name: Run Lint command
              run: npm run prettier:check
            - name: Run Prettier command
              run: npm run lint:check
            - name: Run Prettier command
              run: npm run build
            